### ISSUE TITLE
Project Request

### ISSUE THREAD

**Issue by kreviceko** [codeitlikemiley/vuetified#11]
@codeitlikemiley I've really enjoyed this - so thank you very much. 
Is it possible to do this same setup except using the quasar framework?
I'm too thick to get the passport authentication stuff to work as it should, hence why I love this vuetified.
However, I think I'd like the way quasar framework is set up (more complete?).

**Comment by codeitlikemiley** [comment]
i know quasar but , i havent got free time , to create a starter app with that  stack...
