### ISSUE TITLE
Uncaught ReferenceError: webpackJsonp is not defined

### ISSUE THREAD

**Issue by leon0399** [codeitlikemiley/vuetified#17]
When compiling `production` assets with `yarn prod`, there is an error on the page, and nothing showing except spinner

```
Uncaught ReferenceError: webpackJsonp is not defined
    at app.js?id=4510d0b84af0f58015f3:1
(anonymous) @ app.js?id=4510d0b84af0f58015f3:1
```

Seems like this error is caused because files `0.js`, `1.js`, etc doesn't load to the page

**Comment by rosnaib11** [comment]
Same issue here

**Comment by codeitlikemiley** [comment]
If you do yarn prod, 
you need to change your .env
APP_ENV=production 
That should resolve your issue
