### ISSUE TITLE
Install sequence that worked for me

### ISSUE THREAD

**Issue by adavie1** [codeitlikemiley/vuetified#20]
I believe the `readme.md` is a bit out of date, at least for Ubuntu, this is the sequence that worked for me:

1. `git clone https://github.com/codeitlikemiley/vuetified YOURPROJECTNAME`
2. `cd YOURPROJECTNAME`
3.  `sudo apt-get install php-imagick`
4. `composer require spatie/pdf-to-image`
5. `composer install`
6. `yarn`
7. `cp .env.example .env` // edit .env with DB details, used: `nano .env`
8. `php artisan key:generate`
9. `php artisan migrate:fresh --seed`
10. `php artisan passport:install`

To launch on localhost: `php artisan serve`

**Comment by connecteev** [comment]
Doesnt work on mac:

Tried this but this doesnt work either
```
brew search imagick
brew install php72-imagick
```

**Comment by connecteev** [comment]
Update: Was able to install image magick on Mac using:
```brew install imagemagick```
However, running ```composer require spatie/pdf-to-image``` gives this error:
```
$ composer require spatie/pdf-to-image
Using version ^1.8 for spatie/pdf-to-image
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/pdf-to-image 1.8.1 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.
    - spatie/pdf-to-image 1.8.2 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.
    - spatie/pdf-to-image 1.8.1 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.
    - spatie/pdf-to-image 1.8.0 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.
    - Installation request for spatie/pdf-to-image ^1.8 -> satisfiable by spatie/pdf-to-image[1.8.0, 1.8.1, 1.8.2].

  To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/etc/php/7.3/php.ini
    - /usr/local/etc/php/7.3/conf.d/ext-opcache.ini
    - /usr/local/etc/php/7.3/conf.d/php-memory-limits.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.


```

**Comment by adavie1** [comment]
@connecteev I'm not a Mac user, neither am I associated with this project, I put there to help others.
