### ISSUE TITLE
Readme typography / styling

### ISSUE THREAD

**Issue by nkbrs** [codeitlikemiley/vuetified#4]
I wanted to use your app, I really did. But why is every word uppercased? You gave me a vertigo, I can't read that at all. 

Friendly advice - don't do that. Don't uppercase every word. It's IMPOSSIBLE to read.

Best of luck.

**Comment by codeitlikemiley** [comment]
uppercased on documentation?

**Comment by lcherone** [comment]
I Noticed This To, I'm Not Sure Why You Have Made Every Sentence A Title, It Makes It Hard To Read..

vs.

I noticed this to, I'm not sure why you have made every sentence a title, it makes it hard to read..

also i is always I..
