### ISSUE TITLE
Missing step in the installation: Migration and key:generate

### ISSUE THREAD

**Issue by matthiku** [codeitlikemiley/vuetified#8]
Before you can run `php artisan passport:install` you must run `php artisan migrate`.
Also, after creating .env, run `php artisan key:generate`

Unrelated: Can I ignore these warnings from `yarn install`:

> warning " > babel-loader@7.1.2" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
> warning " > babel-loader@7.1.2" has unmet peer dependency "webpack@2 || 3".
> warning " > vue-loader@13.6.0" has unmet peer dependency "css-loader@*".
> warning " > mocha-webpack@1.0.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0".

**Comment by codeitlikemiley** [comment]
that is totally normal having a warning
